# Generated by Django 3.1.2 on 2020-10-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20201008_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='person',
            name='sender',
            field=models.CharField(default='PyWisher', max_length=100),
            preserve_default=False,
        ),
    ]
